# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suboffice',
            name='anaptuksiakes',
            field=models.DecimalField(decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='suboffice',
            name='pagio',
            field=models.DecimalField(decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='suboffice',
            name='taktikes',
            field=models.DecimalField(decimal_places=3, max_digits=18, null=True),
        ),
    ]
