# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisations', '0002_auto_20160720_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suboffice',
            name='approved',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='suboffice',
            name='revised',
            field=models.NullBooleanField(),
        ),
    ]
