# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisations', '0003_auto_20160720_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suboffice',
            name='subOfficeId',
            field=models.CharField(max_length=6),
        ),
    ]
