# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisations', '0004_auto_20160723_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='approved',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='office',
            name='revised',
            field=models.NullBooleanField(),
        ),
    ]
