# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisations', '0006_auto_20160726_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='year',
            field=models.IntegerField(),
        ),
    ]
